#FROM node:20-alpine
#
#WORKDIR /Users/nabyeongho/Desktop/self_study/our-trip/our-trip-back
#
#COPY ./package.json ./
#
#RUN npm install
#
#COPY ./ ./
#
#CMD ["npm", "run", "start"]

# ====================

#FROM diamol/node
#
#ENV TARGET="blog.sixeyed.com"
#ENV method="HEAD"
#ENV INTERVAL="3000"
#
#WORKDIR /web-ping
#COPY app.js .

#CMD ["node", "/web-ping/app.js"]

WORKDIR /usr