name: Github Action docker image

on:
  push:
#    branches: [ "main" ]
    branches: [ "master" ]

jobs:

  our-trip-back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: use node.js
        uses: actions/setup-node@v2
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t manaweb-api .
      - name: taging
        run: docker tag manaweb-api:latest mag123c/manaweb-api:latest
      - name: Push to Dockerhub
        run: docker push mag123c/manaweb-api:latest